micronaut:
  application:
    name: epmloyee-service
datasources:
  default:
    url: jdbc:postgresql://192.168.0.12:5432/employee
    username: postgres
    password: pass
    driverClassName: org.postgresql.Driver
jpa:
  default:
    packages-to-scan:
      - 'epmloyee.service.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

